function normalizeModeTags(tags: unknown): string[] {
  if (!tags) return []
  if (Array.isArray(tags)) {
    return tags
      .map((tag) => (typeof tag === 'string' ? tag.trim() : ''))
      .filter(Boolean)
  }
  if (typeof tags === 'string') {
    return tags
      .split(',')
      .map((tag) => tag.trim())
      .filter(Boolean)
  }
  return []
}

import { API_CONFIG } from '@/config/api'
import {
  buildJourneyTemplateData,
  getJourneyTemplateById as getLocalTemplateById,
  listJourneyTemplates as listLocalTemplates,
  type JourneyTemplate,
  type JourneyTemplateDay,
  type JourneyTemplateTask,
  type JourneyTemplateTimeSlot,
} from '@/data/journeyTemplates'

export interface JourneyTemplateListParams {
  status?: 'draft' | 'published' | 'archived'
  mode?: 'inspiration' | 'planner' | 'seeker'
  keyword?: string
  page?: number
  limit?: number
  modePrimary?: string
  modeTags?: string | string[]
}

export interface JourneyTemplateListItem {
  id: string
  title: string
  mode: 'inspiration' | 'planner' | 'seeker'
  status?: 'draft' | 'published' | 'archived'
  modePrimary?: string | null
  modeTags?: string[] | string | null
  coverImage?: string
  durationDays?: number
  summary?: string
  description?: string
  coreInsight?: string
  journeyBackground?: string[]
  personaProfile?: Record<string, any>
  journeyDesign?: Record<string, any>
  tasksDefault?: any[]
  createdAt?: string
  updatedAt?: string
}

export interface JourneyTemplateListResponse {
  data: JourneyTemplateListItem[]
  total: number
  page: number
  limit: number
}

interface JourneyTemplateDetailTimeSlot {
  id?: string
  sequence?: number
  startTime?: string
  durationMinutes?: number | null
  type?: string
  title?: string
  activityHighlights?: { text?: string }
  scenicIntro?: string
  locationJson?: { name?: string }
  detailsJson?: {
    transport?: {
      mode?: string
      details?: string
      metrics?: {
        distanceKm?: number
        durationMinutes?: number
      }
    }
    tips?: string[]
  }
}

interface JourneyTemplateDetailDay {
  id?: string
  dayNumber: number
  title: string
  summary?: string
  detailsJson?: any
  timeSlots?: JourneyTemplateDetailTimeSlot[]
}

export interface JourneyTemplateDetail extends JourneyTemplateListItem {
  days?: JourneyTemplateDetailDay[]
  mentalFlowStages?: Record<string, any>
}

function buildEndpoint(path: string, params?: Record<string, any>) {
  const base = (API_CONFIG.BASE_URL || window.location.origin).replace(/\/$/, '')
  const normalizedPath = path.startsWith('/') ? path : `/${path}`
  const url = new URL(`${base}${normalizedPath}`)
  if (params) {
    Object.entries(params).forEach(([key, value]) => {
      if (value === undefined || value === null || value === '') return
      url.searchParams.set(key, String(value))
    })
  }
  return url.toString()
}

function toHours(minutes?: number | null) {
  if (!minutes || Number.isNaN(minutes)) return undefined
  const hours = minutes / 60
  return Math.round(hours * 10) / 10
}

function generateId(prefix: string) {
  if (typeof crypto !== 'undefined' && typeof crypto.randomUUID === 'function') {
    return crypto.randomUUID()
  }
  return `${prefix}_${Date.now()}_${Math.random().toString(16).slice(2)}`
}

function normalizeTask(task: any): JourneyTemplateTask {
  return {
    id: task?.id || generateId('task'),
    title: task?.title || task?.name || '',
    autoGenerated: Boolean(task?.autoGenerated),
    autoKey: task?.autoKey || undefined,
    category: task?.category || 'general',
    links: Array.isArray(task?.links)
      ? task.links
          .map((link: any) => ({
            name: link?.name || link?.title || '了解更多',
            url: link?.url || link?.link,
          }))
          .filter((link: any) => link.name && link.url)
      : undefined,
  }
}

function normalizeTimeSlots(
  dayId: string,
  dayNumber: number,
  slots: JourneyTemplateDetailTimeSlot[] = [],
): JourneyTemplateTimeSlot[] {
  return slots.map((slot, index) => ({
    title: slot?.title || `时段 ${index + 1}`,
    type: (slot?.type || 'activity') as string,
    startTime: slot?.startTime || '',
    durationHours: toHours(slot?.durationMinutes ?? slot?.detailsJson?.transport?.metrics?.durationMinutes),
    location: slot?.locationJson?.name || '',
    activityHighlights: slot?.activityHighlights?.text || '',
    scenicIntro: slot?.scenicIntro || '',
    localTip: Array.isArray(slot?.detailsJson?.tips) ? slot?.detailsJson?.tips?.[0] : undefined,
    transport: slot?.detailsJson?.transport
      ? {
          mode: slot.detailsJson.transport.mode,
          details: slot.detailsJson.transport.details,
          metrics: slot.detailsJson.transport.metrics,
        }
      : undefined,
  }))
}

function normalizeDays(detail: JourneyTemplateDetail): JourneyTemplateDay[] {
  if (!Array.isArray(detail.days)) return []
  return detail.days.map((day, index) => ({
    day: day?.dayNumber ?? index + 1,
    title: day?.title || `第${day?.dayNumber ?? index + 1}天`,
    summary: day?.summary || '',
    timeSlots: normalizeTimeSlots(day?.id || '', day?.dayNumber ?? index + 1, day?.timeSlots),
  }))
}

export function convertApiTemplateDetail(detail: JourneyTemplateDetail): JourneyTemplate {
  const location =
    (detail as any).location ||
    (detail as any).destination ||
    detail.summary ||
    detail.title ||
    '未知目的地'

  return {
    id: detail.id,
    mode: detail.mode || 'inspiration',
    status: detail.status,
    modePrimary: detail.modePrimary || undefined,
    modeTags: normalizeModeTags(detail.modeTags),
    title: detail.title,
    coverImage: detail.coverImage || '',
    location,
    duration: detail.durationDays || detail.days?.length || 1,
    summary: detail.summary || '',
    description: detail.description || '',
    coreInsight: detail.coreInsight || '',
    journeyBackground: Array.isArray(detail.journeyBackground) ? detail.journeyBackground : [],
    personaProfile: detail.personaProfile as any,
    journeyDesign: detail.journeyDesign as any,
    mentalFlowStages: detail.mentalFlowStages as any,
    tasks: Array.isArray(detail.tasksDefault) ? detail.tasksDefault.map(normalizeTask) : [],
    days: normalizeDays(detail),
    createdAt: detail.createdAt,
    updatedAt: detail.updatedAt,
  }
}

export interface JourneyTemplateListResult extends JourneyTemplateListResponse {
  fallback?: boolean
}

export async function fetchJourneyTemplates(params: JourneyTemplateListParams = {}): Promise<JourneyTemplateListResult> {
  const endpoint = buildEndpoint('/api/v1/templates', {
    status: params.status,
    mode: params.mode,
    modePrimary: params.modePrimary,
    modeTags: Array.isArray(params.modeTags) ? params.modeTags.join(',') : params.modeTags,
    keyword: params.keyword,
    page: params.page || 1,
    limit: params.limit || 20,
  })

  if (typeof window !== 'undefined') {
    console.log('[JourneyTemplateAPI] -> list url', endpoint)
  }

  const response = await fetch(endpoint, {
    headers: { 'Content-Type': 'application/json' },
  })

  if (!response.ok) {
    throw new Error(`Failed to load templates: ${response.status}`)
  }

  const data = await response.json()
  if (typeof window !== 'undefined') {
    console.log('[JourneyTemplateAPI] <- raw response', data)
  }
  const normalized = (data?.data || []).map((item: JourneyTemplateListItem & { modeTags?: string | string[] | null }) => ({
    ...item,
    modePrimary: item.modePrimary || undefined,
    modeTags: normalizeModeTags(item.modeTags),
  }))
  if (typeof window !== 'undefined') {
    console.log('[JourneyTemplateAPI] normalized length', normalized.length)
  }
  return {
    ...(data as JourneyTemplateListResponse),
    data: normalized,
    fallback: false,
  }
}

export async function fetchJourneyTemplateDetail(id: string) {
  const endpoint = buildEndpoint(`/api/v1/templates/${id}`)
  const response = await fetch(endpoint, {
    headers: { 'Content-Type': 'application/json' },
  })

  if (!response.ok) {
    throw new Error(`Failed to load template detail: ${response.status}`)
  }

  const data = (await response.json()) as JourneyTemplateDetail
  const template = convertApiTemplateDetail(data)
  return {
    raw: data,
    template,
    inspiration: buildJourneyTemplateData(template),
    fallback: false,
  }
}

export async function fetchJourneyTemplatesWithFallback(params: JourneyTemplateListParams = {}): Promise<JourneyTemplateListResult> {
  try {
    return await fetchJourneyTemplates(params)
  } catch (error) {
    console.warn('Template list API failed, fallback to local data', error)
    const local = listLocalTemplates()
    const requestedTags =
      Array.isArray(params.modeTags)
        ? params.modeTags
        : typeof params.modeTags === 'string' && params.modeTags.trim()
          ? params.modeTags.split(',').map((tag) => tag.trim()).filter(Boolean)
          : []
    const filtered = local.filter((item) => {
      const statusMatch = !params.status || (item.status || 'published') === params.status
      const modeMatch = !params.mode || item.mode === params.mode
      const primaryMatch = !params.modePrimary || item.modePrimary === params.modePrimary
      const tagMatch =
        !requestedTags.length ||
        (Array.isArray(item.modeTags) && requestedTags.every((tag) => item.modeTags?.includes(tag)))
      if (!statusMatch || !modeMatch || !primaryMatch || !tagMatch) return false
      if (!params.keyword) return true
      const query = params.keyword.toLowerCase()
      const haystack = [
        item.title,
        item.summary,
        item.description,
        item.coreInsight,
        ...(item.journeyBackground || []),
      ]
        .filter(Boolean)
        .join(' ')
        .toLowerCase()
      return haystack.includes(query)
    })

    const page = params.page || 1
    const limit = params.limit || 20
    const start = (page - 1) * limit
    const sliced = filtered.slice(start, start + limit)

    const result: JourneyTemplateListResult = {
      data: sliced.map((item) => ({
        id: item.id,
        title: item.title,
        mode: item.mode,
        status: item.status,
        modePrimary: item.modePrimary,
        modeTags: Array.isArray(item.modeTags) ? item.modeTags : normalizeModeTags(item.modeTags),
        coverImage: item.coverImage,
        durationDays: item.duration,
        summary: item.summary,
        description: item.description,
        coreInsight: item.coreInsight,
        journeyBackground: item.journeyBackground,
        personaProfile: item.personaProfile,
        journeyDesign: item.journeyDesign,
        tasksDefault: item.tasks,
        createdAt: item.createdAt,
        updatedAt: item.updatedAt,
      })),
      total: filtered.length,
      page,
      limit,
      fallback: true,
    }

    return result
  }
}

export async function fetchJourneyTemplateDetailWithFallback(id: string) {
  try {
    return await fetchJourneyTemplateDetail(id)
  } catch (error) {
    console.warn('Template detail API failed, fallback to local data', error)
    const local = getLocalTemplateById(id)
    if (!local) {
      throw error
    }
    return {
      raw: local,
      template: local,
      inspiration: buildJourneyTemplateData(local),
      fallback: true,
    }
  }
}

