export interface JourneyTemplateTaskLink {
  name: string
  url: string
}

export interface JourneyTemplateTask {
  id: string
  title: string
  autoGenerated?: boolean
  autoKey?: string
  category: string
  links?: JourneyTemplateTaskLink[]
}

export interface JourneyTemplateTimeSlot {
  title: string
  type: string
  startTime?: string
  durationHours?: number
  location?: string
  activityHighlights?: string
  scenicIntro?: string
  localTip?: string
  transport?: {
    mode?: string
  }
}

export interface JourneyTemplateDay {
  day: number
  title: string
  summary: string
  timeSlots: JourneyTemplateTimeSlot[]
}

export interface JourneyTemplatePersonaProfile {
  type: string
  motivation: string
  dominantEmotion: string
  travelRhythm: string
  socialPreference: string
  cognitiveNeed: string
  foodPreference?: string
}

export interface JourneyTemplateJourneyDesign {
  coreInsight: string
  psychologicalFlow: string[]
  symbolicElements: string[]
  recommendedRhythm?: string
  socialMode?: string
}

export interface JourneyTemplateMentalFlowStage {
  theme: string
  activities?: string[]
  emotionalGoal?: string
  symbolicElement?: string
}

export interface JourneyTemplateMentalFlowStages {
  summon?: JourneyTemplateMentalFlowStage
  reflection?: JourneyTemplateMentalFlowStage
  awakening?: JourneyTemplateMentalFlowStage
  internalization?: JourneyTemplateMentalFlowStage
  transformation?: JourneyTemplateMentalFlowStage
}

export interface JourneyTemplate {
  id: string
  mode: 'inspiration' | 'planner' | 'seeker'
  status?: 'draft' | 'published' | 'archived'
  modePrimary?: string
  modeTags?: string[]
  title: string
  coverImage: string
  location: string
  duration: number
  summary: string
  description: string
  coreInsight: string
  safetyNotice?: string
  safetyNotices?: Record<string, string>
  journeyBackground?: string[]
  personaProfile?: JourneyTemplatePersonaProfile
  journeyDesign?: JourneyTemplateJourneyDesign
  mentalFlowStages?: JourneyTemplateMentalFlowStages
  tasks?: JourneyTemplateTask[]
  days: JourneyTemplateDay[]
  createdAt?: string
  updatedAt?: string
}

const JOURNEY_TEMPLATES: JourneyTemplate[] = [
  {
    id: 'svalbard-greenland-arctic-expedition-21d',
    mode: 'inspiration',
    status: 'published',
    modePrimary: '极地探险',
    modeTags: ['科考船', '野生动物', '长线'],
    title: '北极熊王国与冰川之都：斯瓦尔巴德+格陵兰岛深度探险',
    coverImage: 'https://source.unsplash.com/1600x900/?arctic,polar,bear,iceberg',
    location: '斯瓦尔巴德群岛 · 格陵兰岛 · 挪威',
    duration: 21,
    summary: '一次追寻北极之王与冰原奇观的终极探险，穿越北纬80度，深入斯瓦尔巴德无人区，探访格陵兰世界遗产冰峡湾，完成北极探险家的梦想。',
    description:
      '21天北极双岛深度探险行程，涵盖奥斯陆文化、斯瓦尔巴德群岛环游（穿越北纬80度）、寻觅北极熊等野生动物，以及格陵兰伊卢利萨特冰峡湾徒步、艾奇冰川巡游和因纽特文化体验。',
    coreInsight:
      '8月北极盛夏，是斯瓦尔巴德海冰融化、通行条件最佳，也是观赏北极熊与格陵兰冰川崩解活动的黄金季节。独家安排巡游超级冰川，提供远超常规路线的深度体验。',
    safetyNotice:
      '斯瓦尔巴德行程为真正的探险，路线完全由天气、冰况和野生动物决定。在北极熊出没区域，必须严格遵守探险队安全规定，全程携带防护设备。',
    safetyNotices: {
      'zh-cn':
        '斯瓦尔巴德行程为真正的探险，路线完全由天气、冰况和野生动物决定。在北极熊出没区域，必须严格遵守探险队安全规定，全程携带防护设备。',
      en:
        'Svalbard itinerary is a true expedition, entirely dependent on weather, ice, and wildlife. Strictly follow safety protocols in polar bear country; carry protective equipment at all times during landings.',
    },
    journeyBackground: [
      '斯瓦尔巴德群岛是北极熊王国，数量超过居民，8月是乘船环游和观测的最佳窗口。',
      '格陵兰伊卢利萨特冰峡湾是北半球最活跃的冰川，每日崩解的冰量惊人，是世界自然遗产。',
    ],
    personaProfile: {
      type: '硬核探险家与野生动物摄影师',
      motivation: '追寻北极熊的足迹，亲历冰川崩解的轰鸣，抵达常人未至的北极秘境',
      dominantEmotion: '敬畏与探险的兴奋',
      travelRhythm: '高强度探索，日间频繁登陆与巡游，夜晚讲座分享',
      socialPreference: '与探险队员和同好者紧密互动，分享发现与技巧',
      cognitiveNeed: '深入了解北极生态系统、冰川学与极地探险历史',
      foodPreference: '适应船餐，期待在格陵兰品尝当地简餐',
    },
    journeyDesign: {
      coreInsight: '北极野生动物追寻 + 世界级冰川地貌探索',
      psychologicalFlow: ['北欧都市启程', '北极荒野觉醒', '北极熊王国探险', '格陵兰冰川震撼', '文化体验与归程'],
      symbolicElements: ['北极熊', '冰川', '午夜太阳', '因纽特'],
      recommendedRhythm: '斯瓦尔巴德段：全天候弹性探险；格陵兰段：固定行程与自由探索结合',
      socialMode: '探险船上的集体科考队模式',
    },
    mentalFlowStages: {
      summon: {
        theme: '奥斯陆，北极之门',
        activities: ['维格朗雕塑公园', '奥斯陆市政厅'],
        emotionalGoal: '从人文艺术过渡到自然探险的期待',
        symbolicElement: '雕塑《生命之柱》',
      },
      reflection: {
        theme: '驶向斯瓦尔巴德',
        activities: ['朗伊尔城历史了解', '登船启航'],
        emotionalGoal: '感受逐渐远离文明，进入荒野的氛围',
      },
      awakening: {
        theme: '北极熊王国的召唤',
        activities: ['穿越北纬80度', '首次北极熊观测', '巡游超级冰川'],
        emotionalGoal: '亲历北极荒野的原始力量与生命奇迹',
      },
      internalization: {
        theme: '格陵兰的冰与火之歌',
        activities: ['伊卢利萨特冰峡湾徒步', '艾奇冰川巡游', '午夜阳光之旅'],
        emotionalGoal: '沉浸于冰川世界的壮美与因纽特文化的韧性',
      },
      transformation: {
        theme: '告别冰原，满载而归',
        activities: ['努克博物馆参观', '哥本哈根返程'],
        emotionalGoal: '将北极的震撼转化为对地球环境的深层认知与责任感',
      },
    },
    tasks: [
      {
        id: 'task_auto_arctic_gear',
        title: '准备专业极地装备：高倍望远镜、长焦镜头、防风防水外套、保暖层',
        autoGenerated: true,
        autoKey: 'gear_arctic_expedition',
        category: 'gear',
      },
      {
        id: 'task_auto_bear_safety',
        title: '学习并理解北极熊安全守则',
        autoGenerated: true,
        autoKey: 'safety_polar_bear',
        category: 'safety',
        links: [
          {
            name: '斯瓦尔巴德总督府游客指南',
            url: 'https://www.sysselmesteren.no/en/visitors/',
          },
        ],
      },
      {
        id: 'task_auto_travel_insurance',
        title: '购买包含紧急救援和极地行程的专项旅行保险',
        autoGenerated: true,
        autoKey: 'documents_travel_insurance_arctic',
        category: 'documents',
      },
    ],
    days: [
      {
        day: 1,
        title: '中国 -> 奥斯陆（夜宿航班）',
        summary: '搭乘国际航班飞往挪威首都奥斯陆。',
        timeSlots: [
          {
            title: '机场集合与飞行',
            type: 'transport',
            startTime: '晚上',
            durationHours: 24,
            location: '国际航班',
            activityHighlights: '办理登机手续，开启前往北极门户的旅程。',
            transport: {
              mode: 'flight',
            },
          },
        ],
      },
      {
        day: 2,
        title: '抵达奥斯陆',
        summary: '抵达奥斯陆，入住酒店调整时差。',
        timeSlots: [
          {
            title: '抵达与入住',
            type: 'arrival',
            startTime: '上午',
            durationHours: 2,
            location: '奥斯陆酒店',
            activityHighlights: '导游接机，前往市区酒店办理入住。',
            transport: {
              mode: 'private_transfer',
            },
          },
        ],
      },
      {
        day: 3,
        title: '奥斯陆文化与飞往北极',
        summary: '游览奥斯陆城市精华，傍晚飞往斯瓦尔巴德首府朗伊尔城。',
        timeSlots: [
          {
            title: '维格朗雕塑公园',
            type: 'culture',
            startTime: '上午',
            durationHours: 2,
            location: '维格朗雕塑公园',
            activityHighlights: '欣赏192座描绘人生百态的青铜与花岗岩雕塑，包括著名的《生命之柱》。',
            scenicIntro: '这是世界上最大的由单一艺术家打造的雕塑公园。',
          },
          {
            title: '奥斯陆市政厅',
            type: 'culture',
            startTime: '下午',
            durationHours: 1.5,
            location: '奥斯陆市政厅',
            activityHighlights: '参观诺贝尔和平奖颁奖典礼举办地，了解挪威历史文化。',
          },
          {
            title: '飞往朗伊尔城',
            type: 'transport',
            startTime: '傍晚',
            durationHours: 3,
            location: '奥斯陆 -> 朗伊尔城',
            activityHighlights: '飞行穿越北极圈，抵达世界最北的城镇。',
            transport: {
              mode: 'flight',
            },
          },
        ],
      },
      {
        day: 4,
        title: '朗伊尔城 & 登船启航',
        summary: '探索北极煤矿小镇，下午登船，航向北极梦幻之境。',
        timeSlots: [
          {
            title: '朗伊尔城探索',
            type: 'sightseeing',
            startTime: '上午',
            durationHours: 2,
            location: '朗伊尔城',
            activityHighlights: '参观小镇博物馆或北极探险相关纪念地，感受极地生活。',
            scenicIntro: '朗伊尔城（北纬78度）是世界上最北的人类居住地之一，以前是煤炭开采镇。',
          },
          {
            title: '登船与安全演习',
            type: 'transport',
            startTime: '下午',
            durationHours: 3,
            location: '朗伊尔城码头',
            activityHighlights: '办理登船手续，参加强制性安全演习和北极熊防护培训。',
            transport: {
              mode: 'ship',
            },
          },
          {
            title: '启航进入冰原',
            type: 'cruise',
            startTime: '傍晚',
            durationHours: 2,
            location: '伊斯峡湾',
            activityHighlights: '船只缓缓驶出峡湾，开始真正的北极探险。',
          },
        ],
      },
      {
        day: 5,
        title: '斯瓦尔巴德西部峡湾探索',
        summary: '根据冰情与天气，开始首次登陆或巡游，寻觅野生动物。',
        timeSlots: [
          {
            title: '首次橡皮艇巡游/登陆',
            type: 'nature',
            startTime: '上午',
            durationHours: 3,
            location: '如Bellsund或Van Keulenfjorden',
            activityHighlights: '在探险队带领下，寻找海象、驯鹿的踪迹，观察丰富的苔原植物。',
            scenicIntro: '斯瓦尔巴德的峡湾在夏季充满生机。',
          },
          {
            title: '北极生态讲座',
            type: 'education',
            startTime: '下午',
            durationHours: 1.5,
            location: '船上讲座室',
            activityHighlights: '学习关于北极熊、海象、斯瓦尔巴德驯鹿等野生动物的知识。',
          },
        ],
      },
      {
        day: 6,
        title: '向东北航行，穿越北纬80度',
        summary: '向斯瓦尔巴德更偏远、冰况更好的东北部地区进发，增加发现北极熊的机会。',
        timeSlots: [
          {
            title: '甲板守望与航行',
            type: 'nature',
            startTime: '全天',
            durationHours: 8,
            location: '斯瓦尔巴德北部海域',
            activityHighlights: '在甲板上用望远镜持续扫描海冰与海岸，寻找北极熊、北极狐的踪迹。',
            localTip: '穿戴保暖，防风是甲板观测的关键。双筒望远镜为必备。',
          },
          {
            title: '穿越北纬80度仪式',
            type: 'community',
            startTime: '傍晚',
            durationHours: 1,
            activityHighlights: '举行小型庆祝仪式，纪念抵达地球顶端附近的非凡纬度。',
          },
        ],
      },
      {
        day: 7,
        title: '北极核心区：七岛群岛',
        summary: '探索斯瓦尔巴德最北端的群岛，这里是北极熊和海象的重要栖息地。',
        timeSlots: [
          {
            title: 'Phippsøya岛附近巡游',
            type: 'cruise',
            startTime: '上午',
            durationHours: 2,
            location: '七岛群岛',
            activityHighlights: '橡皮艇巡游于浮冰之间，在世界上最北的陆地之一寻找北极熊。',
            scenicIntro: '七岛群岛是斯瓦尔巴德最北的陆地，几乎终年被海冰覆盖。',
          },
          {
            title: '冰上观测',
            type: 'nature',
            startTime: '下午',
            durationHours: 3,
            activityHighlights: '船只在海冰边缘缓慢航行，探险队员和专业向导在船头集中观测。',
          },
        ],
      },
      {
        day: 8,
        title: 'Hinlopen海峡与北极鸟崖',
        summary: '穿越雄伟的Hinlopen海峡，参观巨大的海鸟悬崖。',
        timeSlots: [
          {
            title: 'Alkefjellet鸟崖巡游',
            type: 'nature',
            startTime: '上午',
            durationHours: 2,
            location: 'Hinlopen海峡',
            activityHighlights:
              '乘橡皮艇近距离观赏由数十万只厚嘴海鸦筑巢的玄武岩悬崖，景象和声音都极为震撼。',
            scenicIntro: 'Alkefjellet是北极地区最重要的海鸟繁殖地之一。',
          },
          {
            title: '海峡东侧登陆',
            type: 'hiking',
            startTime: '下午',
            durationHours: 3,
            location: '如Augustabukta',
            activityHighlights: '在苔原上徒步，有机会邂逅北极狐，观察古老的捕鲸者遗迹。',
          },
        ],
      },
      {
        day: 9,
        title: '东北地岛与冰瀑布',
        summary: '探访斯瓦尔巴德最大的岛屿，寻找行程亮点之一的超级冰川与冰瀑布。',
        timeSlots: [
          {
            title: '巡游200公里长超级冰川前沿',
            type: 'cruise',
            startTime: '上午',
            durationHours: 3,
            location: '东北地岛冰盖前沿',
            activityHighlights: '船只沿巨大的冰川前沿巡游，亲眼目睹绵延不绝的冰墙和飞泻而下的冰瀑布。',
            scenicIntro: '这是斯瓦尔巴德乃至整个北极地区最壮观的冰川景观之一。',
          },
          {
            title: '冰川学讲座',
            type: 'education',
            startTime: '下午',
            durationHours: 1.5,
            activityHighlights: '由地质学家或冰川学家讲解冰川的形成、运动与对气候的影响。',
          },
        ],
      },
      {
        day: 10,
        title: '西北斯匹次卑尔根国家公园',
        summary: '探索受保护的国家公园，这里拥有深邃的峡湾和丰富的历史遗迹。',
        timeSlots: [
          {
            title: 'Magdalenefjord峡湾登陆',
            type: 'history',
            startTime: '上午',
            durationHours: 2,
            location: 'Magdalenefjord',
            activityHighlights: '参观17世纪捕鲸者的墓地与遗迹，在美丽的海滩漫步。',
            scenicIntro: '这个峡湾是早期北极探险的重要基地，风景如画。',
          },
          {
            title: '峡湾巡游与野生动物观测',
            type: 'cruise',
            startTime: '下午',
            durationHours: 2,
            activityHighlights: '继续在峡湾中寻找髯海豹、环斑海豹和岸边可能出现的北极熊。',
          },
        ],
      },
      {
        day: 11,
        title: '斯瓦尔巴德最后探索',
        summary: '根据最佳天气和动物踪迹，选择最后一个精彩的登陆点。',
        timeSlots: [
          {
            title: '最后一次斯瓦尔巴德登陆/巡游',
            type: 'nature',
            startTime: '上午',
            durationHours: 3,
            location: '由探险队长决定',
            activityHighlights:
              '珍惜在北极熊王国的最后时光，可能是苔原徒步、历史遗迹探访或最后的北极熊守望。',
          },
          {
            title: '航向朗伊尔城',
            type: 'cruise',
            startTime: '下午',
            durationHours: 2,
            activityHighlights: '开始返航，在船上回顾和整理斯瓦尔巴德的照片与笔记。',
          },
        ],
      },
      {
        day: 12,
        title: '下船 & 飞返奥斯陆',
        summary: '清晨抵达朗伊尔城，下船后飞返挪威大陆。',
        timeSlots: [
          {
            title: '下船与告别探险队',
            type: 'departure',
            startTime: '早上',
            durationHours: 1.5,
            location: '朗伊尔城码头',
            activityHighlights: '与共度多日的探险队员和船员告别。',
          },
          {
            title: '飞返奥斯陆',
            type: 'transport',
            startTime: '上午',
            durationHours: 3,
            location: '朗伊尔城 -> 奥斯陆',
            transport: {
              mode: 'flight',
            },
          },
          {
            title: '奥斯陆自由活动',
            type: 'leisure',
            startTime: '下午',
            durationHours: 4,
            location: '奥斯陆',
            activityHighlights: '可自行参观维京船博物馆或于卡尔·约翰斯大道购物休闲。',
          },
        ],
      },
      {
        day: 13,
        title: '奥斯陆 -> 哥本哈根 -> 努克',
        summary: '经哥本哈根转机，飞往格陵兰首府努克。',
        timeSlots: [
          {
            title: '飞往哥本哈根',
            type: 'transport',
            startTime: '上午',
            durationHours: 1.5,
            location: '奥斯陆 -> 哥本哈根',
            transport: {
              mode: 'flight',
            },
          },
          {
            title: '飞往格陵兰努克',
            type: 'transport',
            startTime: '下午',
            durationHours: 4.5,
            location: '哥本哈根 -> 努克',
            activityHighlights: '飞行是一次视觉盛宴，俯瞰格陵兰冰盖边缘。',
            transport: {
              mode: 'flight',
            },
          },
        ],
      },
      {
        day: 14,
        title: '努克文化与历史',
        summary: '探索格陵兰首府，了解因纽特人的历史与生活。',
        timeSlots: [
          {
            title: '格陵兰国家博物馆',
            type: 'culture',
            startTime: '上午',
            durationHours: 2,
            location: '努克',
            activityHighlights: '参观著名的Qilakitsoq木乃伊，了解因纽特人的历史和习俗。',
            scenicIntro: '博物馆虽小，但藏品极具价值，全面展示了格陵兰4000多年的文化。',
          },
          {
            title: '努克教堂与城市景观',
            type: 'sightseeing',
            startTime: '下午',
            durationHours: 2,
            location: '努克',
            activityHighlights: '参观建于1849年的红色木制教堂，在城市至高点欣赏色彩斑斓的房子和峡湾风光。',
          },
        ],
      },
      {
        day: 15,
        title: '飞往冰川之都：伊卢利萨特',
        summary: '抵达伊卢利萨特，傍晚体验永不落幕的午夜阳光游船。',
        timeSlots: [
          {
            title: '努克 -> 伊卢利萨特航班',
            type: 'transport',
            startTime: '上午',
            durationHours: 1.5,
            location: '努克 -> 伊卢利萨特',
            transport: {
              mode: 'flight',
            },
          },
          {
            title: '伊卢利萨特小镇漫步',
            type: 'sightseeing',
            startTime: '下午',
            durationHours: 2,
            location: '伊卢利萨特',
            activityHighlights: '参观彩色房屋，了解小镇历史，感受世界遗产地的独特氛围。',
          },
          {
            title: '午夜阳光游船',
            type: 'cruise',
            startTime: '晚上',
            durationHours: 3,
            location: '迪斯科湾',
            activityHighlights:
              '乘坐特种船，在午夜太阳的照耀下，穿梭于巨大的浮冰之间，近距离观赏世界遗产冰峡湾的入口。',
            scenicIntro: '这是体验伊卢利萨特冰峡湾最令人难忘的方式之一。',
          },
        ],
      },
      {
        day: 16,
        title: '伊卢利萨特冰峡湾徒步',
        summary: '徒步探索世界遗产，多角度欣赏北半球最活跃的冰川。',
        timeSlots: [
          {
            title: '冰峡湾蓝线徒步',
            type: 'hiking',
            startTime: '上午',
            durationHours: 3,
            location: '伊卢利萨特冰峡湾',
            activityHighlights:
              '沿着木栈道徒步至Sermermiut河谷，俯瞰壮丽的冰峡湾全景，聆听冰川崩裂的声音。',
            scenicIntro: '伊卢利萨特冰峡湾在2004年被列为世界自然遗产。',
            localTip: '路径有上下坡，建议使用登山杖以节省体力。',
          },
          {
            title: '冰峡湾黄线徒步',
            type: 'hiking',
            startTime: '下午',
            durationHours: 2.5,
            location: '伊卢利萨特冰峡湾',
            activityHighlights: '更靠近冰缘的徒步路线，有机会从不同角度看到从冰峡湾流出的巨大冰山。',
          },
        ],
      },
      {
        day: 17,
        title: '艾奇冰川全日巡游',
        summary: '搭乘特制船，近距离接触北格陵兰冰山崩裂最为频繁的冰川之一。',
        timeSlots: [
          {
            title: '前往艾奇冰川',
            type: 'cruise',
            startTime: '全天',
            durationHours: 8,
            location: '艾奇冰川',
            activityHighlights:
              '航行至伊卢利萨特以北80公里的艾奇冰川，近距离观赏其宽2.8公里、高达200米的冰墙，期待冰块坠海的震撼瞬间与轰鸣。',
            scenicIntro: '艾奇冰川是伊卢利萨特地区仅次于冰峡湾的又一冰川奇观，活动极为活跃。',
            localTip: '海上温度低，风大，务必穿戴最保暖的衣物。准备晕船药。',
          },
        ],
      },
      {
        day: 18,
        title: '因纽特渔村文化探访',
        summary: '乘船前往附近的因纽特传统渔村，感受最地道的格陵兰生活。',
        timeSlots: [
          {
            title: '乘船前往因纽特渔村',
            type: 'culture',
            startTime: '上午',
            durationHours: 4,
            location: '伊卢利萨特附近渔村（如Ilimanaq）',
            activityHighlights:
              '参观当地历史地标建筑，与村民交流，了解他们的捕猎传统与现代生活。',
            transport: {
              mode: 'boat',
            },
            scenicIntro: '这些宁静的小村庄保留了格陵兰最传统的生活方式。',
          },
        ],
      },
      {
        day: 19,
        title: '伊卢利萨特 -> 努克 -> 哥本哈根',
        summary: '告别冰川之城，经努克转机飞返哥本哈根。',
        timeSlots: [
          {
            title: '飞返哥本哈根',
            type: 'transport',
            startTime: '上午',
            durationHours: 6,
            location: '伊卢利萨特 -> 努克 -> 哥本哈根',
            activityHighlights: '经停努克，换乘国际航班返回丹麦。在飞机上最后俯瞰壮丽的格陵兰景观。',
            transport: {
              mode: 'flight',
            },
          },
        ],
      },
      {
        day: 20,
        title: '哥本哈根 -> 中国',
        summary: '搭乘国际航班返回中国。',
        timeSlots: [
          {
            title: '机场送机与返程',
            type: 'departure',
            startTime: '上午',
            durationHours: 3,
            location: '哥本哈根机场',
            activityHighlights: '办理退税及登机手续，带着北极的震撼回忆踏上归途。',
            transport: {
              mode: 'private_transfer',
            },
          },
        ],
      },
      {
        day: 21,
        title: '抵达中国',
        summary: '抵达国内，圆满结束史诗般的北极双岛探险之旅。',
        timeSlots: [
          {
            title: '抵达与解散',
            type: 'departure',
            startTime: '下午/晚上',
            durationHours: 1,
            location: '国内机场',
            activityHighlights: '抵达国内机场，提取行李，与同行旅伴告别，行程结束。',
          },
        ],
      },
    ],
    createdAt: '2025-01-11T08:00:00.000Z',
    updatedAt: '2025-02-05T12:00:00.000Z',
  },
]

const HOURS_TO_MINUTES = 60

const ensureArray = <T>(value: T | T[] | undefined | null): T[] => {
  if (Array.isArray(value)) {
    return value
  }
  if (value === undefined || value === null) {
    return []
  }
  return [value]
}

const normalizeSlot = (
  templateId: string,
  dayNumber: number,
  slot: JourneyTemplateTimeSlot,
  index: number,
) => {
  const estimatedDuration =
    typeof slot.durationHours === 'number' && slot.durationHours > 0
      ? Math.round(slot.durationHours * HOURS_TO_MINUTES)
      : undefined

  const description =
    slot.scenicIntro || slot.activityHighlights
      ? {
          scenicIntro: slot.scenicIntro || slot.activityHighlights,
          highlights: slot.activityHighlights ? ensureArray(slot.activityHighlights) : [],
        }
      : undefined

  const recommendations = slot.localTip
    ? {
        suitableFor: slot.localTip,
      }
    : undefined

  const transportation = slot.transport
    ? {
        mode: slot.transport.mode,
        metrics: estimatedDuration
          ? {
              estimatedMinutes: estimatedDuration,
              bestLabel: slot.transport.mode ? `建议交通：${slot.transport.mode}` : undefined,
            }
          : undefined,
      }
    : undefined

  return {
    id: `${templateId}-d${dayNumber}-s${index}`,
    title: slot.title,
    activity: slot.title,
    type: slot.type,
    category: slot.type,
    time: slot.startTime || '待定',
    startTime: slot.startTime,
    estimatedDuration,
    duration: estimatedDuration,
    location: slot.location,
    summary: slot.activityHighlights || slot.scenicIntro,
    notes: slot.activityHighlights,
    localTip: slot.localTip,
    details: {
      name: slot.title
        ? {
            chinese: slot.title,
            english: slot.title,
          }
        : undefined,
      description,
      recommendations,
      transportation,
    },
  }
}

const normalizeDay = (template: JourneyTemplate, day: JourneyTemplateDay) => ({
  day: day.day,
  title: day.title,
  summary: day.summary,
  theme: day.title,
  timeSlots: day.timeSlots.map((slot, index) => normalizeSlot(template.id, day.day, slot, index)),
})

export const getJourneyTemplateById = (id: string): JourneyTemplate | undefined =>
  JOURNEY_TEMPLATES.find((item) => item.id === id)

export const buildJourneyTemplateData = (template: JourneyTemplate) => {
  const normalizedDays = template.days.map((day) => normalizeDay(template, day))

  return {
    id: template.id,
    templateId: template.id,
    createdFromTemplate: true,
    generationMode: 'template' as const,
    title: template.title,
    coverImage: template.coverImage,
    location: template.location,
    destination: template.location,
    duration: template.duration,
    summary: template.summary,
    description: template.description,
    coreInsight: template.coreInsight,
    safetyNotice: template.safetyNotice,
    safetyNotices: template.safetyNotices,
    journeyBackground: template.journeyBackground,
    personaProfile: template.personaProfile,
    journeyDesign: template.journeyDesign,
    mentalFlowStages: template.mentalFlowStages,
    tasks: template.tasks,
    days: normalizedDays,
    hasFullItinerary: true,
    mode: template.mode,
    modePrimary: template.modePrimary,
    modeTags: template.modeTags,
  }
}

export const listJourneyTemplates = () => [...JOURNEY_TEMPLATES]


